paths :
  data_folder : data
  train_file: webtext.train.jsonl
  valid_file: webtext.valid.jsonl
  test_file: webtext.test.jsonl

distilled_model:
  nb_layers: 6

training_parameters:
  learning_rate: 0.001
